name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - waveshare-s3-audio
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create secrets.yaml
        run: |
          echo "wifi_ssid: \"${{ secrets.WIFI_SSID }}\"" > secrets.yaml
          echo "wifi_password: \"${{ secrets.WIFI_PASSWORD }}\"" >> secrets.yaml
          echo "api_esp32-audio-s3: \"${{ secrets.API_ENCRYPTION_KEY }}\"" >> secrets.yaml
          echo "ota_password: \"${{ secrets.OTA_PASSWORD }}\"" >> secrets.yaml

      - name: Build ESPHome Firmware
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: stable
